spring.application.name=inspection-map-user-service

# Database configuration
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.datasource.url=jdbc:mysql://localhost:3306/im-user-service?createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=root

# JPA (Hibernate) configuration
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQL8Dialect

# Flyway configuration
spring.flyway.enabled=true